# Generated by Django 4.1.4 on 2022-12-22 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_level', models.IntegerField()),
                ('health_description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=64)),
                ('location_description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=64)),
                ('specie', models.CharField(max_length=32)),
                ('age', models.SmallIntegerField()),
                ('gender', models.CharField(max_length=32)),
                ('appearance_date', models.DateTimeField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='product_image')),
                ('health', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.health_description')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.location')),
            ],
        ),
    ]
