# Generated by Django 3.2.16 on 2022-12-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=80)),
                ('dyn_attr', models.JSONField(blank=True, null=True)),
                ('percent', models.PositiveIntegerField(blank=True, default=0)),
                ('initial_price', models.PositiveIntegerField(blank=True, default=0)),
                ('stock', models.SmallIntegerField(default=0)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='product_image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
