# Generated by Django 4.1.4 on 2022-12-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_animal_is_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='is_given',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
