# Generated by Django 4.1.4 on 2023-01-02 17:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_alter_animal_is_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='booked_by_who',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
