# Generated by Django 4.1.4 on 2023-01-02 17:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_animal_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='animal',
            managers=[
                ('newmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
