# Generated by Django 4.1.4 on 2023-01-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_animal_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='animal',
            managers=[
            ],
        ),
    ]
